### PR TITLE
Remove redundant type=text/ attributes

### PR DESCRIPTION
**Pull request by zdroid**
Not needed in HTML5

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
> Not needed in HTML5
Hey Zlatan,Thanks for the PR,The site is visible at: https://atul1837.github.io/covid/  
@atul1837 will give it a look,then we can merge it..
Do you have more ideas on how we can improve the simulators??

**Comment by ashwani-rathee** [comment]
@zdroid this breaks the site,we will need to look into it

**Comment by zdroid** [comment]
@ashwani-rathee What exactly is broken? I tried this in inspect element in Chrome and it works normally. It probably is some other issue with the site, but I'm willing to look into it and fix it. :smile:

**Comment by ashwani-rathee** [comment]
Thanks for help,We haven't found that but it did caused to break If we find it then we will try to fix it too :)

**Pull request merged**
